kind: ConfigMap
metadata:
  name: config-gateway
  namespace: vanus
apiVersion: v1
data:
  gateway.yaml: |-
    port: 8080
    sink_port: 8082
    controllers:
      - vanus-controller-0.vanus-controller:2048
      - vanus-controller-1.vanus-controller:2048
      - vanus-controller-2.vanus-controller:2048
    observability:
      metrics:
        enable: true
      tracing:
        enable: false
---
apiVersion: v1
kind: Service
metadata:
  name: vanus-gateway
  namespace: vanus
spec:
  ports:
    - name: proxy
      targetPort: 8080
      port: 8080
    - name: cloudevents
      targetPort: 8081
      port: 8081
  selector:
    app: vanus-gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vanus-gateway
  name: vanus-gateway
  namespace: vanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanus-gateway
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: vanus-gateway
    spec:
      nodeSelector:
        type: calculation
      containers:
        - image: public.ecr.aws/vanus/gateway:6b23e5a
          imagePullPolicy: IfNotPresent
          name: gateway
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 2000m
              memory: 2000Mi
          ports:
            - containerPort: 8080
              name: proxy
            - containerPort: 8081
              name: cloudevents
            - containerPort: 8082
              name: sinkproxy
#            - containerPort: 2112
#              protocol: TCP
#              name: metrics
          volumeMounts:
            - mountPath: /vanus/config
              name: config-gateway
        - name: node-exporter
          image: prom/node-exporter
          args:
            - --no-collector.wifi
            - --no-collector.hwmon
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)
            - --collector.netclass.ignored-devices=^(veth.*)$
          ports:
            - containerPort: 9100
              protocol: TCP
              name: metrics
          resources:
            limits:
              cpu: 250m
              memory: 180Mi
            requests:
              cpu: 102m
              memory: 180Mi
      volumes:
        - configMap:
            name: config-gateway
          name: config-gateway
