apiVersion: v1
kind: Service
metadata:
  name: vanus-gateway
  namespace: vanus
spec:
  selector:
    app: vanus-gateway
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      name: proxy
    - port: 8081
      targetPort: 8081
      nodePort: 30002
      name: cloudevents
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-gateway
  namespace: vanus
data:
  gateway.yaml: |-
    port: 8080
    sink_port: 8082
    controllers:
      - vanus-controller-0.vanus-controller:2048
      - vanus-controller-1.vanus-controller:2048
      - vanus-controller-2.vanus-controller:2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanus-gateway
  namespace: vanus
  labels:
    app: vanus-gateway
spec:
  selector:
    matchLabels:
      app: vanus-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: vanus-gateway
      annotations:
        vanus.dev/metrics.port: "2112"
    spec:
      containers:
        - name: gateway
          image: public.ecr.aws/vanus/gateway:v0.7.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: proxy
              containerPort: 8080
            - name: cloudevents
              containerPort: 8081
            - name: sinkproxy
              containerPort: 8082
          env:
            - name: VANUS_LOG_LEVEL
              value: INFO
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: config-gateway
              mountPath: /vanus/config
      volumes:
        - name: config-gateway
          configMap:
            name: config-gateway
